# Generated by Django 6.0.5 on 2026-05-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='discription',
        ),
        migrations.AddField(
            model_name='bug',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.CharField(default='open', max_length=20),
        ),
    ]
